/* clang-format off */
/* AUTO-GENERATED by tools/regmap/regmap_gen.py - DO NOT EDIT.
 * Source: icd/address_map.yaml
 * Hardware baseline: hw-v2 */
#ifndef SATLINK_REGS_ADDRESS_MAP_H
#define SATLINK_REGS_ADDRESS_MAP_H

/* ---- ps: Zynq PS address space as seen by the Cortex-A9 cores (PL blocks via M_AXI_GP0) (GIC interrupt ID) ---- */

/* 1 GiB DDR3L, partitioned for AMP (see DDR partitions) [owner: shared, fixed] */
#define SATLINK_PS_DDR_BASE (0x00000000U)
#define SATLINK_PS_DDR_SIZE (0x40000000U)

/* Modem symbol TX / baseband RX DMA [owner: rtos, provisional] */
#define SATLINK_PS_AXI_DMA_MODEM_BASE (0x40400000U)
#define SATLINK_PS_AXI_DMA_MODEM_SIZE (0x00010000U)
#define SATLINK_PS_AXI_DMA_MODEM_IRQ_MM2S (61U)
#define SATLINK_PS_AXI_DMA_MODEM_IRQ_S2MM (62U)

/* Frame accelerator loopback DMA [owner: linux, provisional] */
#define SATLINK_PS_AXI_DMA_FRAME_BASE (0x40410000U)
#define SATLINK_PS_AXI_DMA_FRAME_SIZE (0x00010000U)
#define SATLINK_PS_AXI_DMA_FRAME_IRQ_MM2S (65U)
#define SATLINK_PS_AXI_DMA_FRAME_IRQ_S2MM (66U)

/* Spectrum monitor FFT output DMA [owner: linux, provisional] */
#define SATLINK_PS_AXI_DMA_SPEC_BASE (0x40420000U)
#define SATLINK_PS_AXI_DMA_SPEC_SIZE (0x00010000U)
#define SATLINK_PS_AXI_DMA_SPEC_IRQ_S2MM (68U)

/* LEDs LD0-3 (ch1), buttons BTN0-3 (ch2) [owner: rtos, provisional] */
#define SATLINK_PS_AXI_GPIO_0_BASE (0x41200000U)
#define SATLINK_PS_AXI_GPIO_0_SIZE (0x00010000U)
#define SATLINK_PS_AXI_GPIO_0_IRQ_GPIO (64U)

/* Modem control: NCOs, channel emulator, RX packetizer [owner: rtos, provisional] */
#define SATLINK_PS_PAYLOAD_CTRL_BASE (0x43C00000U)
#define SATLINK_PS_PAYLOAD_CTRL_SIZE (0x00010000U)
#define SATLINK_PS_PAYLOAD_CTRL_IRQ_STATUS (63U)

/* CCSDS randomizer + CRC-16 accelerator [owner: linux, provisional] */
#define SATLINK_PS_CCSDS_FRAME_ACCEL_BASE (0x43C10000U)
#define SATLINK_PS_CCSDS_FRAME_ACCEL_SIZE (0x00010000U)
#define SATLINK_PS_CCSDS_FRAME_ACCEL_IRQ_FRAME_DONE (67U)

/* Spectrum tap: Hann window and frame gate in front of the FFT [owner: linux, provisional] */
#define SATLINK_PS_SPEC_TAP_BASE (0x43C20000U)
#define SATLINK_PS_SPEC_TAP_SIZE (0x00010000U)

/* FreeRTOS console (EMIO, Pmod JE1/JE2) [owner: rtos, fixed] */
#define SATLINK_PS_PS_UART0_BASE (0xE0000000U)
#define SATLINK_PS_PS_UART0_SIZE (0x00001000U)
#define SATLINK_PS_PS_UART0_IRQ_UART (59U)

/* Linux console (on-board USB-UART, ttyPS0) [owner: linux, fixed] */
#define SATLINK_PS_PS_UART1_BASE (0xE0001000U)
#define SATLINK_PS_PS_UART1_SIZE (0x00001000U)
#define SATLINK_PS_PS_UART1_IRQ_UART (82U)

/* SSM2603 codec configuration (EMIO) [owner: linux, fixed] */
#define SATLINK_PS_PS_I2C0_BASE (0xE0004000U)
#define SATLINK_PS_PS_I2C0_SIZE (0x00001000U)
#define SATLINK_PS_PS_I2C0_IRQ_I2C (57U)

/* PmodCAN #1 (MCP2515) on Pmod JF, MIO 10..15 [owner: linux, fixed] */
#define SATLINK_PS_PS_SPI1_BASE (0xE0007000U)
#define SATLINK_PS_PS_SPI1_SIZE (0x00001000U)
#define SATLINK_PS_PS_SPI1_IRQ_SPI (81U)

/* MIO GPIO (MIO0 = PmodCAN #1 INT) [owner: linux, fixed] */
#define SATLINK_PS_PS_GPIO_BASE (0xE000A000U)
#define SATLINK_PS_PS_GPIO_SIZE (0x00001000U)
#define SATLINK_PS_PS_GPIO_IRQ_GPIO (52U)

/* Gigabit Ethernet [owner: linux, fixed] */
#define SATLINK_PS_PS_GEM0_BASE (0xE000B000U)
#define SATLINK_PS_PS_GEM0_SIZE (0x00001000U)
#define SATLINK_PS_PS_GEM0_IRQ_ETH (54U)

/* SD card (boot + root filesystem) [owner: linux, fixed] */
#define SATLINK_PS_PS_SD0_BASE (0xE0100000U)
#define SATLINK_PS_PS_SD0_SIZE (0x00001000U)
#define SATLINK_PS_PS_SD0_IRQ_SD (56U)

/* FreeRTOS profiling timer [owner: rtos, fixed] */
#define SATLINK_PS_PS_TTC1_BASE (0xF8002000U)
#define SATLINK_PS_PS_TTC1_SIZE (0x00001000U)
#define SATLINK_PS_PS_TTC1_IRQ_TIMER0 (69U)
#define SATLINK_PS_PS_TTC1_IRQ_TIMER1 (70U)
#define SATLINK_PS_PS_TTC1_IRQ_TIMER2 (71U)

/* System watchdog (FDIR, Stage 6) [owner: linux, fixed] */
#define SATLINK_PS_PS_SWDT_BASE (0xF8005000U)
#define SATLINK_PS_PS_SWDT_SIZE (0x00001000U)
#define SATLINK_PS_PS_SWDT_IRQ_WDT (41U)

/* ---- hkc: MicroBlaze V (housekeeping controller) data address space (AXI INTC input) ---- */

/* Bootloader (reset vector), baked into the bitstream [owner: hkc, provisional] */
#define SATLINK_HKC_LMB_BOOTLOADER_BASE (0x00000000U)
#define SATLINK_HKC_LMB_BOOTLOADER_SIZE (0x00004000U)

/* Application image, loaded by the bootloader over CAN [owner: hkc, provisional] */
#define SATLINK_HKC_LMB_APP_BASE (0x00004000U)
#define SATLINK_HKC_LMB_APP_SIZE (0x0001C000U)

/* Switches SW0-3 (ch1), RGB LED6 (ch2) [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_GPIO_BASE (0x40000000U)
#define SATLINK_HKC_HKC_GPIO_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_GPIO_IRQ_GPIO (6U)

/* MCU console (Pmod JE7/JE8) [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_UART_BASE (0x40600000U)
#define SATLINK_HKC_HKC_UART_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_UART_IRQ_UART (4U)

/* AXI interrupt controller [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_INTC_BASE (0x41200000U)
#define SATLINK_HKC_HKC_INTC_SIZE (0x00010000U)

/* Timebase watchdog (resets the MCU subsystem only) [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_WDT_BASE (0x41A00000U)
#define SATLINK_HKC_HKC_WDT_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_WDT_IRQ_WDT (0U)

/* Tick and timestamp timer [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_TIMER_BASE (0x41C00000U)
#define SATLINK_HKC_HKC_TIMER_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_TIMER_IRQ_TIMER (1U)

/* AXI Quad SPI to PmodCAN #2 (Pmod JB) [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_SPI_BASE (0x44A00000U)
#define SATLINK_HKC_HKC_SPI_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_SPI_IRQ_SPI (3U)
#define SATLINK_HKC_HKC_SPI_IRQ_CAN2_INT (2U)

/* XADC Wizard: die temperature and supply voltages [owner: hkc, provisional] */
#define SATLINK_HKC_HKC_XADC_BASE (0x44A10000U)
#define SATLINK_HKC_HKC_XADC_SIZE (0x00010000U)
#define SATLINK_HKC_HKC_XADC_IRQ_XADC (5U)

/* ---- DDR partitions (AMP) ---- */

/* Linux kernel and user space (896 MiB) [owner: linux, provisional] */
#define SATLINK_DDR_LINUX_BASE (0x00000000U)
#define SATLINK_DDR_LINUX_SIZE (0x38000000U)

/* FreeRTOS image, heap and stacks (16 MiB) [owner: rtos, provisional] */
#define SATLINK_DDR_RTOS_FW_BASE (0x38000000U)
#define SATLINK_DDR_RTOS_FW_SIZE (0x01000000U)

/* OpenAMP vrings and RPMsg buffers (1 MiB) [owner: shared, provisional] */
#define SATLINK_DDR_RPMSG_SHM_BASE (0x39000000U)
#define SATLINK_DDR_RPMSG_SHM_SIZE (0x00100000U)

/* Modem DMA buffer descriptors and sample buffers (15 MiB) [owner: rtos, provisional] */
#define SATLINK_DDR_MODEM_DMA_BASE (0x39100000U)
#define SATLINK_DDR_MODEM_DMA_SIZE (0x00F00000U)

/* Reserved for later stages (96 MiB) [owner: shared, provisional] */
#define SATLINK_DDR_RESERVED_BASE (0x3A000000U)
#define SATLINK_DDR_RESERVED_SIZE (0x06000000U)

#endif /* SATLINK_REGS_ADDRESS_MAP_H */
