/* clang-format off */
// AUTO-GENERATED by tools/regmap/regmap_gen.py - DO NOT EDIT.
// Source: icd/regmap/ccsds_frame_accel.yaml
#pragma once

#include <cstdint>

#include "satlink/regdef.hpp"

namespace satlink::regs::ccsds_frame_accel {

inline constexpr std::uint32_t kSpan = 0x18U;

/// VERSION: Block version.
namespace version {
inline constexpr Register kReg{0x00U, Access::kReadOnly, 0x00010000U};
inline constexpr Field kMinor{0x00U, 0U, 16U, Access::kReadOnly};
inline constexpr Field kMajor{0x00U, 16U, 16U, Access::kReadOnly};
} // namespace version

/// CTRL: Control bits.
namespace ctrl {
inline constexpr Register kReg{0x04U, Access::kReadWrite, 0x00000000U};
inline constexpr Field kRandomizerEn{0x04U, 0U, 1U, Access::kReadWrite};
inline constexpr Field kIrqEn{0x04U, 1U, 1U, Access::kReadWrite};
} // namespace ctrl

/// STATUS: Sticky event flags; write 1 to clear.
namespace status {
inline constexpr Register kReg{0x08U, Access::kWrite1Clear, 0x00000000U};
inline constexpr Field kFrameDone{0x08U, 0U, 1U, Access::kWrite1Clear};
} // namespace status

/// CRC: CRC-16-CCITT (init 0xFFFF) of the last output frame. Reads 0x0000 when the frame ends with a valid big-endian FECF.
namespace crc {
inline constexpr Register kReg{0x0CU, Access::kReadOnly, 0x0000FFFFU};
inline constexpr Field kValue{0x0CU, 0U, 16U, Access::kReadOnly};
} // namespace crc

/// LAST_LEN: Length of the last frame in bytes.
namespace last_len {
inline constexpr Register kReg{0x10U, Access::kReadOnly, 0x00000000U};
inline constexpr Field kBytes{0x10U, 0U, 24U, Access::kReadOnly};
} // namespace last_len

/// FRAME_CNT: Number of frames processed since reset.
namespace frame_cnt {
inline constexpr Register kReg{0x14U, Access::kReadOnly, 0x00000000U};
inline constexpr Field kCount{0x14U, 0U, 32U, Access::kReadOnly};
} // namespace frame_cnt

} // namespace satlink::regs::ccsds_frame_accel
