/* clang-format off */
// AUTO-GENERATED by tools/regmap/regmap_gen.py - DO NOT EDIT.
// Source: icd/regmap/payload_ctrl.yaml
#pragma once

#include <cstdint>

#include "satlink/regdef.hpp"

namespace satlink::regs::payload_ctrl {

inline constexpr std::uint32_t kSpan = 0x24U;

/// VERSION: Block version.
namespace version {
inline constexpr Register kReg{0x00U, Access::kReadOnly, 0x00020000U};
inline constexpr Field kMinor{0x00U, 0U, 16U, Access::kReadOnly};
inline constexpr Field kMajor{0x00U, 16U, 16U, Access::kReadOnly};
} // namespace version

/// CTRL: Control bits.
namespace ctrl {
inline constexpr Register kReg{0x04U, Access::kReadWrite, 0x00000000U};
inline constexpr Field kRxEn{0x04U, 0U, 1U, Access::kReadWrite};
inline constexpr Field kDigLoopback{0x04U, 1U, 1U, Access::kReadWrite};
inline constexpr Field kCodecUnmute{0x04U, 2U, 1U, Access::kReadWrite};
inline constexpr Field kIrqEn{0x04U, 3U, 1U, Access::kReadWrite};
} // namespace ctrl

/// STATUS: Sticky event flags; write 1 to clear.
namespace status {
inline constexpr Register kReg{0x08U, Access::kWrite1Clear, 0x00000000U};
inline constexpr Field kTxUnderrun{0x08U, 0U, 1U, Access::kWrite1Clear};
inline constexpr Field kRxOverrun{0x08U, 1U, 1U, Access::kWrite1Clear};
} // namespace status

/// TX_PINC: TX NCO phase increment. A write sends one configuration beat to tx_nco. f_carrier = PINC / 2^32 * 48 kHz (0x40000000 = 12 kHz).
namespace tx_pinc {
inline constexpr Register kReg{0x0CU, Access::kReadWrite, 0x40000000U};
inline constexpr Field kPinc{0x0CU, 0U, 32U, Access::kReadWrite};
} // namespace tx_pinc

/// RX_PINC: RX NCO phase increment (rx_nco outputs e^-jwt). A write sends one beat to rx_nco.
namespace rx_pinc {
inline constexpr Register kReg{0x10U, Access::kReadWrite, 0x40000000U};
inline constexpr Field kPinc{0x10U, 0U, 32U, Access::kReadWrite};
} // namespace rx_pinc

/// RX_FRAME_LEN: Number of baseband samples per DMA packet (TLAST period).
namespace rx_frame_len {
inline constexpr Register kReg{0x14U, Access::kReadWrite, 0x00000400U};
inline constexpr Field kLen{0x14U, 0U, 16U, Access::kReadWrite};
} // namespace rx_frame_len

/// NOISE_LEVEL: Channel emulator noise amplitude.
namespace noise_level {
inline constexpr Register kReg{0x18U, Access::kReadWrite, 0x00000000U};
inline constexpr Field kLevel{0x18U, 0U, 16U, Access::kReadWrite};
} // namespace noise_level

/// RX_SAMPLE_CNT: Free-running count of RX baseband samples.
namespace rx_sample_cnt {
inline constexpr Register kReg{0x1CU, Access::kReadOnly, 0x00000000U};
inline constexpr Field kCount{0x1CU, 0U, 32U, Access::kReadOnly};
} // namespace rx_sample_cnt

/// ATTEN: Channel emulator linear gain.
namespace atten {
inline constexpr Register kReg{0x20U, Access::kReadWrite, 0x00007FFFU};
inline constexpr Field kGainQ15{0x20U, 0U, 16U, Access::kReadWrite};
} // namespace atten

} // namespace satlink::regs::payload_ctrl
