/* clang-format off */
// AUTO-GENERATED by tools/regmap/regmap_gen.py - DO NOT EDIT.
// Source: icd/regmap/spec_tap.yaml
#pragma once

#include <cstdint>

#include "satlink/regdef.hpp"

namespace satlink::regs::spec_tap {

inline constexpr std::uint32_t kSpan = 0x10U;

/// VERSION: Block version.
namespace version {
inline constexpr Register kReg{0x00U, Access::kReadOnly, 0x00010000U};
inline constexpr Field kMinor{0x00U, 0U, 16U, Access::kReadOnly};
inline constexpr Field kMajor{0x00U, 16U, 16U, Access::kReadOnly};
} // namespace version

/// CTRL: Control bits.
namespace ctrl {
inline constexpr Register kReg{0x04U, Access::kReadWrite, 0x00000000U};
inline constexpr Field kEnable{0x04U, 0U, 1U, Access::kReadWrite};
inline constexpr Field kWindowEn{0x04U, 1U, 1U, Access::kReadWrite};
} // namespace ctrl

/// STATUS: Capture status.
namespace status {
inline constexpr Register kReg{0x08U, Access::kWrite1Clear, 0x00000000U};
inline constexpr Field kBusy{0x08U, 0U, 1U, Access::kReadOnly};
inline constexpr Field kFrameDropped{0x08U, 1U, 1U, Access::kWrite1Clear};
} // namespace status

/// FRAME_CNT: Number of frames sent to the FFT.
namespace frame_cnt {
inline constexpr Register kReg{0x0CU, Access::kReadOnly, 0x00000000U};
inline constexpr Field kCount{0x0CU, 0U, 32U, Access::kReadOnly};
} // namespace frame_cnt

} // namespace satlink::regs::spec_tap
