#!/usr/bin/env python3
"""Generate the requirements traceability matrix from source-code tags.

Requirements live in docs/requirements/*.sdoc (StrictDoc). Source files link to them with
comment tags:

    @implements SRS-<AREA>-<NNN>    this file implements the requirement
    @verifies   SRS-<AREA>-<NNN>    this file verifies (tests) the requirement

The matrix is written to docs/traceability/traceability.md.

Usage:
    python3 tools/trace/trace_matrix.py            # regenerate the matrix
    python3 tools/trace/trace_matrix.py --check    # CI: unknown UIDs or stale matrix -> exit 1

@implements SRS-DOC-002
"""
from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_SDOC_DIR = REPO_ROOT / "docs" / "requirements"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "traceability" / "traceability.md"

TAG_RE = re.compile(r"@(implements|verifies)\s+(SRS-[A-Z]+-\d{3})\b")
UID_LINE = re.compile(r"^UID:\s*(\S+)\s*$", re.M)
TITLE_LINE = re.compile(r"^TITLE:\s*(.+?)\s*$", re.M)
STATUS_LINE = re.compile(r"^STATUS:\s*(\S+)\s*$", re.M)

SCANNED_SUFFIXES = {
    ".c", ".h", ".cpp", ".hpp", ".py", ".cmake", ".yml", ".yaml", ".bb", ".bbappend",
    ".bbclass", ".conf", ".cfg", ".inc", ".sh", ".wks", ".cmd", ".dts", ".dtsi", ".v", ".sv",
    ".vhd", ".tcl", ".xdc",
}
SCANNED_NAMES = {"CMakeLists.txt"}
EXCLUDED_DIRS = {".git", "build", "_deps", "__pycache__", ".venv", "node_modules"}


@dataclasses.dataclass(frozen=True)
class Requirement:
    uid: str
    title: str
    status: str
    document: str


@dataclasses.dataclass
class Trace:
    implemented_by: set[str] = dataclasses.field(default_factory=set)
    verified_by: set[str] = dataclasses.field(default_factory=set)


def parse_requirements(sdoc_dir: pathlib.Path) -> dict[str, Requirement]:
    """Read every [REQUIREMENT] block from the .sdoc files in sdoc_dir."""
    reqs: dict[str, Requirement] = {}
    for sdoc in sorted(sdoc_dir.glob("*.sdoc")):
        text = sdoc.read_text(encoding="utf-8")
        for block in text.split("[REQUIREMENT]")[1:]:
            uid = UID_LINE.search(block)
            if uid is None:
                raise ValueError(f"{sdoc.name}: requirement without UID")
            title = TITLE_LINE.search(block)
            status = STATUS_LINE.search(block)
            key = uid.group(1)
            if key in reqs:
                raise ValueError(f"{sdoc.name}: duplicate requirement UID {key}")
            reqs[key] = Requirement(key, title.group(1) if title else "(no title)",
                                    status.group(1) if status else "Draft", sdoc.name)
    return reqs


def _candidate_files(root: pathlib.Path) -> list[pathlib.Path]:
    try:
        listed = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard"],
                                cwd=root, capture_output=True, text=True, check=True).stdout
        files = [root / line for line in listed.splitlines() if line]
    except (OSError, subprocess.CalledProcessError):
        files = [p for p in root.rglob("*")
                 if p.is_file() and not EXCLUDED_DIRS.intersection(p.relative_to(root).parts)]
    return sorted(p for p in files
                  if p.is_file() and (p.suffix in SCANNED_SUFFIXES or p.name in SCANNED_NAMES))


def scan_tags(root: pathlib.Path) -> list[tuple[str, str, str]]:
    """Return (kind, uid, relative path) for every tag found under root."""
    found = []
    for path in _candidate_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        rel = path.relative_to(root).as_posix()
        for match in TAG_RE.finditer(text):
            found.append((match.group(1), match.group(2), rel))
    return found


def build(root: pathlib.Path, sdoc_dir: pathlib.Path) -> tuple[str, list[str]]:
    """Return (markdown, errors)."""
    reqs = parse_requirements(sdoc_dir)
    traces = {uid: Trace() for uid in reqs}
    errors = []
    for kind, uid, rel in scan_tags(root):
        if uid not in traces:
            errors.append(f"{rel}: @{kind} references unknown requirement {uid}")
            continue
        (traces[uid].implemented_by if kind == "implements" else traces[uid].verified_by).add(rel)

    accepted = [r for r in reqs.values() if r.status == "Accepted"]
    implemented = sum(1 for r in accepted if traces[r.uid].implemented_by)
    verified = sum(1 for r in accepted if traces[r.uid].verified_by)

    lines = [
        "<!-- AUTO-GENERATED by tools/trace/trace_matrix.py - DO NOT EDIT. -->",
        "# Requirements traceability matrix",
        "",
        "Generated from `@implements` / `@verifies` tags in the source tree.",
        "",
        f"- Requirements: {len(reqs)} ({len(accepted)} accepted)",
        f"- Accepted and implemented: {implemented} / {len(accepted)}",
        f"- Accepted and verified by an automated test: {verified} / {len(accepted)}",
        "",
        "| UID | Title | Status | Implemented by | Verified by |",
        "|---|---|---|---|---|",
    ]
    for uid in sorted(reqs):
        req, trace = reqs[uid], traces[uid]
        impl = "<br>".join(f"`{p}`" for p in sorted(trace.implemented_by)) or "-"
        ver = "<br>".join(f"`{p}`" for p in sorted(trace.verified_by)) or "-"
        lines.append(f"| {uid} | {req.title} | {req.status} | {impl} | {ver} |")
    lines.append("")
    return "\n".join(lines), errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--root", type=pathlib.Path, default=REPO_ROOT)
    parser.add_argument("--sdoc-dir", type=pathlib.Path, default=None)
    parser.add_argument("--output", type=pathlib.Path, default=None)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 on unknown UIDs or a stale matrix")
    args = parser.parse_args(argv)
    sdoc_dir = args.sdoc_dir or args.root / "docs" / "requirements"
    output = args.output or args.root / "docs" / "traceability" / "traceability.md"

    try:
        markdown, errors = build(args.root, sdoc_dir)
    except ValueError as exc:
        print(f"trace_matrix: error: {exc}", file=sys.stderr)
        return 2
    for err in errors:
        print(f"trace_matrix: error: {err}", file=sys.stderr)

    current = output.read_text(encoding="utf-8") if output.exists() else None
    if args.check:
        if current != markdown:
            print(f"trace_matrix: {output} is out of date; run tools/trace/trace_matrix.py",
                  file=sys.stderr)
            return 1
        return 1 if errors else 0

    if current != markdown:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(markdown, encoding="utf-8", newline="\n")
        print(f"trace_matrix: wrote {output}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
