#!/usr/bin/env python3
"""Generate C/C++ register headers and Markdown ICD pages from the YAML files in icd/.

The YAML files are the single source of truth for every software/FPGA interface
(ADR-0002). This tool validates them and writes:

* libs/regs/include/satlink/regs/<block>.h / .hpp   register maps
* libs/regs/include/satlink/regs/address_map.h      base addresses, sizes, IRQs, DDR partitions
* docs/icd/generated/*.md                           human-readable ICD pages

Usage:
    python3 tools/regmap/regmap_gen.py            # regenerate all outputs
    python3 tools/regmap/regmap_gen.py --check    # fail if outputs are out of date (CI)

@implements SRS-ICD-001
@implements SRS-ICD-002
@implements SRS-ICD-003
@implements SRS-ICD-004
"""
from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import sys
from typing import Any

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_ICD_DIR = REPO_ROOT / "icd"
DEFAULT_INCLUDE_DIR = REPO_ROOT / "libs" / "regs" / "include" / "satlink" / "regs"
DEFAULT_DOCS_DIR = REPO_ROOT / "docs" / "icd" / "generated"

ACCESS_TYPES = ("RO", "RW", "WO", "W1C")
CPP_ACCESS = {
    "RO": "Access::kReadOnly",
    "RW": "Access::kReadWrite",
    "WO": "Access::kWriteOnly",
    "W1C": "Access::kWrite1Clear",
}
OWNERS = ("linux", "rtos", "hkc", "shared")
STATUSES = ("fixed", "provisional", "frozen")
MAX_BLOCK_SPAN = 0x10000

UPPER_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")
LOWER_NAME = re.compile(r"^[a-z][a-z0-9_]*$")
BITS_SPEC = re.compile(r"^\s*(\d+)\s*(?::\s*(\d+)\s*)?$")

GENERATED_NOTE = "AUTO-GENERATED by tools/regmap/regmap_gen.py - DO NOT EDIT."


class RegmapError(Exception):
    """Raised when an ICD file is invalid."""


# --------------------------------------------------------------------------------------------
# Data model
# --------------------------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Field:
    name: str
    msb: int
    lsb: int
    access: str
    description: str

    @property
    def width(self) -> int:
        return self.msb - self.lsb + 1

    @property
    def mask(self) -> int:
        return ((1 << self.width) - 1) << self.lsb

    @property
    def bits(self) -> str:
        return str(self.lsb) if self.msb == self.lsb else f"{self.msb}:{self.lsb}"


@dataclasses.dataclass(frozen=True)
class Register:
    name: str
    offset: int
    access: str
    reset: int
    description: str
    fields: tuple[Field, ...]


@dataclasses.dataclass(frozen=True)
class Block:
    name: str
    description: str
    registers: tuple[Register, ...]
    source: str

    @property
    def span(self) -> int:
        return max(r.offset for r in self.registers) + 4


@dataclasses.dataclass(frozen=True)
class Region:
    name: str
    base: int
    size: int
    owner: str
    status: str
    description: str
    irqs: tuple[tuple[str, int], ...]
    regmap: str | None
    ip: str | None


@dataclasses.dataclass(frozen=True)
class Space:
    name: str
    description: str
    irq_kind: str
    regions: tuple[Region, ...]


@dataclasses.dataclass(frozen=True)
class AddressMap:
    hardware_baseline: str
    spaces: tuple[Space, ...]
    ddr_partitions: tuple[Region, ...]


# --------------------------------------------------------------------------------------------
# Parsing and validation
# --------------------------------------------------------------------------------------------


def _int(value: Any, what: str) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, str)):
        raise RegmapError(f"{what}: expected an integer, got {value!r}")
    try:
        return value if isinstance(value, int) else int(value, 0)
    except ValueError as exc:
        raise RegmapError(f"{what}: invalid integer {value!r}") from exc


def _str(mapping: dict[str, Any], key: str, what: str, default: str | None = None) -> str:
    value = mapping.get(key, default)
    if not isinstance(value, str) or not value.strip():
        raise RegmapError(f"{what}: missing or empty '{key}'")
    return " ".join(value.split())


def _parse_bits(spec: Any, what: str) -> tuple[int, int]:
    match = BITS_SPEC.match(str(spec))
    if match is None:
        raise RegmapError(f"{what}: bits must look like '7:0' or '3', got {spec!r}")
    msb = int(match.group(1))
    lsb = int(match.group(2)) if match.group(2) is not None else msb
    if not 0 <= lsb <= msb <= 31:
        raise RegmapError(f"{what}: bits {spec!r} outside 31..0 or msb < lsb")
    return msb, lsb


def _parse_field(raw: dict[str, Any], reg_name: str, reg_access: str, what: str) -> Field:
    name = _str(raw, "name", what)
    if not UPPER_NAME.match(name):
        raise RegmapError(f"{what}: field name {name!r} must be UPPER_SNAKE_CASE")
    msb, lsb = _parse_bits(raw.get("bits"), f"{what} field {name}")
    access = raw.get("access", reg_access)
    if access not in ACCESS_TYPES:
        raise RegmapError(f"{what} field {name}: access {access!r} not in {ACCESS_TYPES}")
    return Field(name, msb, lsb, access, _str(raw, "description", f"{what} field {name}"))


def _parse_register(raw: dict[str, Any], what: str) -> Register:
    name = _str(raw, "name", what)
    if not UPPER_NAME.match(name):
        raise RegmapError(f"{what}: register name {name!r} must be UPPER_SNAKE_CASE")
    what = f"{what} register {name}"
    offset = _int(raw.get("offset"), f"{what} offset")
    if offset % 4 != 0:
        raise RegmapError(f"{what}: offset 0x{offset:X} is not 32-bit aligned")
    if not 0 <= offset < MAX_BLOCK_SPAN:
        raise RegmapError(f"{what}: offset 0x{offset:X} outside the 64 KiB block window")
    access = raw.get("access")
    if access not in ACCESS_TYPES:
        raise RegmapError(f"{what}: access {access!r} not in {ACCESS_TYPES}")
    reset = _int(raw.get("reset", 0), f"{what} reset")
    if not 0 <= reset <= 0xFFFFFFFF:
        raise RegmapError(f"{what}: reset value does not fit in 32 bits")

    raw_fields = raw.get("fields")
    if not isinstance(raw_fields, list) or not raw_fields:
        raise RegmapError(f"{what}: needs at least one field")
    fields = tuple(_parse_field(f, name, access, what) for f in raw_fields)

    used = 0
    names: set[str] = set()
    for field in fields:
        if field.name in names:
            raise RegmapError(f"{what}: duplicate field {field.name}")
        names.add(field.name)
        if used & field.mask:
            raise RegmapError(f"{what}: field {field.name} overlaps another field")
        used |= field.mask
    if reset & ~used:
        raise RegmapError(f"{what}: reset 0x{reset:08X} sets bits outside all fields")

    return Register(name, offset, access, reset, _str(raw, "description", what),
                    tuple(sorted(fields, key=lambda f: f.lsb)))


def load_block(path: pathlib.Path) -> Block:
    """Load and validate one register-map YAML file."""
    what = path.name
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise RegmapError(f"{what}: top level must be a mapping")
    name = _str(raw, "block", what)
    if not LOWER_NAME.match(name):
        raise RegmapError(f"{what}: block name {name!r} must be lower_snake_case")
    if name != path.stem:
        raise RegmapError(f"{what}: block name {name!r} must match the file name")
    raw_regs = raw.get("registers")
    if not isinstance(raw_regs, list) or not raw_regs:
        raise RegmapError(f"{what}: needs at least one register")
    registers = tuple(_parse_register(r, what) for r in raw_regs)

    seen_names: set[str] = set()
    seen_offsets: dict[int, str] = {}
    for reg in registers:
        if reg.name in seen_names:
            raise RegmapError(f"{what}: duplicate register {reg.name}")
        seen_names.add(reg.name)
        if reg.offset in seen_offsets:
            raise RegmapError(
                f"{what}: registers {seen_offsets[reg.offset]} and {reg.name} share offset "
                f"0x{reg.offset:02X}")
        seen_offsets[reg.offset] = reg.name

    return Block(name, _str(raw, "description", what),
                 tuple(sorted(registers, key=lambda r: r.offset)), path.name)


def _parse_region(raw: dict[str, Any], what: str) -> Region:
    name = _str(raw, "name", what)
    if not LOWER_NAME.match(name):
        raise RegmapError(f"{what}: region name {name!r} must be lower_snake_case")
    what = f"{what} {name}"
    base = _int(raw.get("base"), f"{what} base")
    size = _int(raw.get("size"), f"{what} size")
    if size <= 0 or base < 0 or base + size > 0x1_0000_0000:
        raise RegmapError(f"{what}: base/size outside the 32-bit address space")
    if base % 4096 != 0:
        raise RegmapError(f"{what}: base 0x{base:08X} is not 4 KiB aligned")
    owner = raw.get("owner")
    if owner not in OWNERS:
        raise RegmapError(f"{what}: owner {owner!r} not in {OWNERS}")
    status = raw.get("status")
    if status not in STATUSES:
        raise RegmapError(f"{what}: status {status!r} not in {STATUSES}")
    irqs_raw = raw.get("irqs", {}) or {}
    if not isinstance(irqs_raw, dict):
        raise RegmapError(f"{what}: irqs must be a mapping name -> number")
    irqs = []
    for irq_name, irq in irqs_raw.items():
        if not LOWER_NAME.match(str(irq_name)):
            raise RegmapError(f"{what}: irq name {irq_name!r} must be lower_snake_case")
        irqs.append((str(irq_name), _int(irq, f"{what} irq {irq_name}")))
    regmap = raw.get("regmap")
    ip = raw.get("ip")
    return Region(name, base, size, owner, status, _str(raw, "description", what),
                  tuple(irqs), str(regmap) if regmap else None, str(ip) if ip else None)


def _check_overlaps(regions: tuple[Region, ...], what: str) -> None:
    ordered = sorted(regions, key=lambda r: r.base)
    for prev, cur in zip(ordered, ordered[1:]):
        if cur.base < prev.base + prev.size:
            raise RegmapError(f"{what}: {prev.name} and {cur.name} overlap")


def load_address_map(path: pathlib.Path, blocks: dict[str, Block]) -> AddressMap:
    """Load and validate the address map, cross-checking register-map references."""
    what = path.name
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict) or not isinstance(raw.get("spaces"), dict):
        raise RegmapError(f"{what}: needs a 'spaces' mapping")

    spaces = []
    for space_name, raw_space in raw["spaces"].items():
        if not LOWER_NAME.match(str(space_name)):
            raise RegmapError(f"{what}: space name {space_name!r} must be lower_snake_case")
        swhat = f"{what} space {space_name}"
        raw_regions = raw_space.get("regions")
        if not isinstance(raw_regions, list) or not raw_regions:
            raise RegmapError(f"{swhat}: needs at least one region")
        regions = tuple(_parse_region(r, swhat) for r in raw_regions)
        names = [r.name for r in regions]
        if len(names) != len(set(names)):
            raise RegmapError(f"{swhat}: duplicate region names")
        _check_overlaps(regions, swhat)
        irq_owner: dict[int, str] = {}
        for region in regions:
            for irq_name, irq in region.irqs:
                if irq in irq_owner:
                    raise RegmapError(
                        f"{swhat}: IRQ {irq} used by both {irq_owner[irq]} and "
                        f"{region.name}.{irq_name}")
                irq_owner[irq] = f"{region.name}.{irq_name}"
            if region.regmap is not None:
                block = blocks.get(region.regmap)
                if block is None:
                    raise RegmapError(f"{swhat}: {region.name} references unknown regmap "
                                      f"{region.regmap!r}")
                if block.span > region.size:
                    raise RegmapError(f"{swhat}: regmap {block.name} does not fit in "
                                      f"{region.name}")
        spaces.append(Space(str(space_name), _str(raw_space, "description", swhat),
                            _str(raw_space, "irq_kind", swhat), regions))

    partitions = tuple(_parse_region(p, f"{what} ddr_partitions")
                       for p in raw.get("ddr_partitions", []) or [])
    if partitions:
        _check_overlaps(partitions, f"{what} ddr_partitions")
        ddr = next((r for s in spaces if s.name == "ps" for r in s.regions if r.name == "ddr"),
                   None)
        if ddr is None:
            raise RegmapError(f"{what}: ddr_partitions need a 'ddr' region in space 'ps'")
        for part in partitions:
            if part.base < ddr.base or part.base + part.size > ddr.base + ddr.size:
                raise RegmapError(f"{what}: DDR partition {part.name} lies outside ps/ddr")

    return AddressMap(_str(raw, "hardware_baseline", what), tuple(spaces), partitions)


def load_icd(icd_dir: pathlib.Path) -> tuple[list[Block], AddressMap]:
    blocks = [load_block(p) for p in sorted((icd_dir / "regmap").glob("*.yaml"))]
    by_name = {b.name: b for b in blocks}
    amap = load_address_map(icd_dir / "address_map.yaml", by_name)
    return blocks, amap


# --------------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------------


def _camel(name: str) -> str:
    return "k" + "".join(part.capitalize() for part in name.lower().split("_"))


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|")


def render_c_header(block: Block) -> str:
    prefix = block.name.upper()
    guard = f"SATLINK_REGS_{prefix}_H"
    out = [
        "/* clang-format off */",
        f"/* {GENERATED_NOTE}",
        f" * Source: icd/regmap/{block.source} */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include \"satlink/regdef.h\"",
        "",
        f"#define {prefix}_SPAN (0x{block.span:02X}U)",
    ]
    for reg in block.registers:
        rp = f"{prefix}_{reg.name}"
        out += ["", f"/* {reg.name} ({reg.access}): {reg.description} */",
                f"#define {rp}_OFFSET (0x{reg.offset:02X}U)",
                f"#define {rp}_RESET (0x{reg.reset:08X}U)"]
        for field in reg.fields:
            fp = f"{rp}_{field.name}"
            out += [f"#define {fp}_SHIFT ({field.lsb}U)",
                    f"#define {fp}_WIDTH ({field.width}U)",
                    f"#define {fp}_MASK (0x{field.mask:08X}U)"]
    out += ["", f"#endif /* {guard} */", ""]
    return "\n".join(out)


def render_cpp_header(block: Block) -> str:
    out = [
        "/* clang-format off */",
        f"// {GENERATED_NOTE}",
        f"// Source: icd/regmap/{block.source}",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "#include \"satlink/regdef.hpp\"",
        "",
        f"namespace satlink::regs::{block.name} {{",
        "",
        f"inline constexpr std::uint32_t kSpan = 0x{block.span:02X}U;",
    ]
    for reg in block.registers:
        acc = CPP_ACCESS[reg.access]
        out += ["", f"/// {reg.name}: {reg.description}",
                f"namespace {reg.name.lower()} {{",
                f"inline constexpr Register kReg{{0x{reg.offset:02X}U, {acc}, 0x{reg.reset:08X}U}};"]
        for field in reg.fields:
            out.append(
                f"inline constexpr Field {_camel(field.name)}{{0x{reg.offset:02X}U, {field.lsb}U, "
                f"{field.width}U, {CPP_ACCESS[field.access]}}};")
        out.append(f"}} // namespace {reg.name.lower()}")
    out += ["", f"}} // namespace satlink::regs::{block.name}", ""]
    return "\n".join(out)


def render_address_map_header(amap: AddressMap) -> str:
    guard = "SATLINK_REGS_ADDRESS_MAP_H"
    out = [
        "/* clang-format off */",
        f"/* {GENERATED_NOTE}",
        " * Source: icd/address_map.yaml",
        f" * Hardware baseline: {amap.hardware_baseline} */",
        f"#ifndef {guard}",
        f"#define {guard}",
    ]
    for space in amap.spaces:
        sp = space.name.upper()
        out += ["", f"/* ---- {space.name}: {space.description} ({space.irq_kind}) ---- */"]
        for region in space.regions:
            rp = f"SATLINK_{sp}_{region.name.upper()}"
            out += ["", f"/* {region.description} [owner: {region.owner}, {region.status}] */",
                    f"#define {rp}_BASE (0x{region.base:08X}U)",
                    f"#define {rp}_SIZE (0x{region.size:08X}U)"]
            for irq_name, irq in region.irqs:
                out.append(f"#define {rp}_IRQ_{irq_name.upper()} ({irq}U)")
    if amap.ddr_partitions:
        out += ["", "/* ---- DDR partitions (AMP) ---- */"]
        for part in amap.ddr_partitions:
            pp = f"SATLINK_DDR_{part.name.upper()}"
            out += ["", f"/* {part.description} [owner: {part.owner}, {part.status}] */",
                    f"#define {pp}_BASE (0x{part.base:08X}U)",
                    f"#define {pp}_SIZE (0x{part.size:08X}U)"]
    out += ["", f"#endif /* {guard} */", ""]
    return "\n".join(out)


def _find_region(amap: AddressMap, block: Block) -> tuple[Space, Region] | None:
    for space in amap.spaces:
        for region in space.regions:
            if region.regmap == block.name:
                return space, region
    return None


def render_block_markdown(block: Block, amap: AddressMap) -> str:
    out = [f"<!-- {GENERATED_NOTE} Source: icd/regmap/{block.source} -->",
           f"# {block.name}", "", block.description, ""]
    located = _find_region(amap, block)
    if located is not None:
        space, region = located
        irqs = ", ".join(f"{n} = {i}" for n, i in region.irqs) or "none"
        out += [f"- **Address space:** {space.name}",
                f"- **Base address:** `0x{region.base:08X}` ({region.status})",
                f"- **Owner:** {region.owner}",
                f"- **Interrupts ({space.irq_kind}):** {irqs}", ""]
    out += ["## Register summary", "", "| Offset | Name | Access | Reset | Description |",
            "|---|---|---|---|---|"]
    for reg in block.registers:
        out.append(f"| `0x{reg.offset:02X}` | {reg.name} | {reg.access} | `0x{reg.reset:08X}` | "
                   f"{_md_escape(reg.description)} |")
    for reg in block.registers:
        out += ["", f"## 0x{reg.offset:02X} {reg.name}", "", _md_escape(reg.description), "",
                "| Bits | Field | Access | Reset | Description |", "|---|---|---|---|---|"]
        for field in reversed(reg.fields):
            reset = (reg.reset & field.mask) >> field.lsb
            out.append(f"| {field.bits} | {field.name} | {field.access} | `0x{reset:X}` | "
                       f"{_md_escape(field.description)} |")
    out.append("")
    return "\n".join(out)


def render_address_map_markdown(amap: AddressMap) -> str:
    out = [f"<!-- {GENERATED_NOTE} Source: icd/address_map.yaml -->",
           "# Address map", "",
           f"Hardware baseline: **{amap.hardware_baseline}**. Status `provisional` values must be "
           "confirmed against the Vivado Address Editor and then set to `frozen`.", ""]
    for space in amap.spaces:
        out += [f"## Space `{space.name}`", "", space.description, "",
                f"| Base | Size | Name | Owner | Interrupts ({space.irq_kind}) | Status | "
                "Description |",
                "|---|---|---|---|---|---|---|"]
        for region in sorted(space.regions, key=lambda r: r.base):
            irqs = ", ".join(f"{n} = {i}" for n, i in region.irqs) or "-"
            name = f"[{region.name}]({region.regmap}.md)" if region.regmap else region.name
            out.append(f"| `0x{region.base:08X}` | `0x{region.size:X}` | {name} | {region.owner} | "
                       f"{irqs} | {region.status} | {_md_escape(region.description)} |")
        out.append("")
    if amap.ddr_partitions:
        out += ["## DDR partitions (AMP)", "", "| Base | Size | Name | Owner | Status | Description |",
                "|---|---|---|---|---|---|"]
        for part in amap.ddr_partitions:
            out.append(f"| `0x{part.base:08X}` | `0x{part.size:X}` | {part.name} | {part.owner} | "
                       f"{part.status} | {_md_escape(part.description)} |")
        out.append("")
    return "\n".join(out)


def render_index_markdown(blocks: list[Block]) -> str:
    out = [f"<!-- {GENERATED_NOTE} -->", "# Generated ICD pages", "",
           "- [Address map](address_map.md)"]
    out += [f"- [{b.name}]({b.name}.md)" for b in blocks]
    out.append("")
    return "\n".join(out)


def generate(icd_dir: pathlib.Path, include_dir: pathlib.Path,
             docs_dir: pathlib.Path) -> dict[pathlib.Path, str]:
    """Return a mapping of output path -> file content."""
    blocks, amap = load_icd(icd_dir)
    outputs: dict[pathlib.Path, str] = {
        include_dir / "address_map.h": render_address_map_header(amap),
        docs_dir / "address_map.md": render_address_map_markdown(amap),
        docs_dir / "README.md": render_index_markdown(blocks),
    }
    for block in blocks:
        outputs[include_dir / f"{block.name}.h"] = render_c_header(block)
        outputs[include_dir / f"{block.name}.hpp"] = render_cpp_header(block)
        outputs[docs_dir / f"{block.name}.md"] = render_block_markdown(block, amap)
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--icd", type=pathlib.Path, default=DEFAULT_ICD_DIR)
    parser.add_argument("--include-dir", type=pathlib.Path, default=DEFAULT_INCLUDE_DIR)
    parser.add_argument("--docs-dir", type=pathlib.Path, default=DEFAULT_DOCS_DIR)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any output is missing or out of date")
    args = parser.parse_args(argv)

    try:
        outputs = generate(args.icd, args.include_dir, args.docs_dir)
    except RegmapError as exc:
        print(f"regmap_gen: error: {exc}", file=sys.stderr)
        return 2

    stale = [p for p, text in outputs.items()
             if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        for path in stale:
            print(f"regmap_gen: out of date: {path}", file=sys.stderr)
        if stale:
            print("regmap_gen: run 'python3 tools/regmap/regmap_gen.py' and commit the result",
                  file=sys.stderr)
        return 1 if stale else 0

    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
        print(f"regmap_gen: wrote {path}")
    if not stale:
        print("regmap_gen: all outputs up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
